### ISSUE TITLE
Move documentation from Wiki to the Repo itself

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Documentation#2]
Since we have a repository for the sole purpose of documentation, it makes no sense to have an empty repo and the docs themselves in the Wiki tab.

If we were documenting a fork of Scholia, that would kind of work, but not here.

**Comment by Lianm123** [comment]
Yep,
So should we simply save the files to the repo instead?  If we make them into .md files, they should be directly readable in the repo, right?

**Comment by AbdBarho** [comment]
closed, see #1
